---
elasticsearch:
  enabled: true
  host: http://172.17.0.2:9200
  username: elastic
  password: elastic

management:
  api_endpoint: "http://172.17.0.3"
  api_port: "8080"

attendance:
  api_endpoint: "http://172.17.0.3"
  api_port: "8081"

salary:
  api_endpoint: "http://172.17.0.3"
  api_port: "8082"

mysql:
  enabled: true
  db_name: "attendancedb"
  host: "172.17.0.5:3306"
  username: root
  password: root
